# Copyright 2019, Oath Inc.
# Licensed under the terms of the Apache 2.0 license.  See the LICENSE file in the project root for terms

version: 4
shared:
    environment:
        CHANGELOG_FILENAME: docs/changelog.md
        DOCUMENTATION_DEBUG: False
        DOCUMENTATION_FORMATS: mkdocs
        PACKAGE_DIR: src
        PACKAGE_DIRECTORY: src
    steps:
        - presetup_deploy_keys: $BASE_PYTHON -m pip install -U .[documentation]
        - tag_release: $BASE_PYTHON -m screwdrivercd.repo.release

jobs:
    validate_codestyle:
        template: python/validate_codestyle
        environment:
            CODESTYLE_ARGS: -v
        requires: [~commit, ~pr]

    validate_codestyle_new:
        template: python/validate_codestyle
        environment:
            CODESTYLE_ARGS: -v
        steps:
            - postinstall_dependencies: $BASE_PYTHON -m pip install -U .
        requires: [~commit, ~pr]

    validate_dependencies:
        template: python/validate_dependencies
        requires: [~commit, ~pr]

    validate_lint:
        template: python/validate_lint
        requires: [~commit, ~pr]

    validate_security:
        template: python/validate_security
        requires: [~commit, ~pr]

    validate_test:
        template: python/validate_unittest
        steps:
            - postupdate_version: |
                PACKAGE_VERSION="`meta get package.version`"
                echo $PACKAGE_VERSION
            - preend: meta set package.version "$PACKAGE_VERSION"
        requires: [~commit, ~pr]

    # The newest version of mypy appears to be broken in a manner that it always flags a specific valid type
    # annotation.
    # validate_type:
    #    template: python/validate_type
    #     requires: [~commit, ~pr]

    validate_documentation:
        template: python/documentation
        environment:
            DOCUMENTATION_PUBLISH: False
        requires: [~pr]

    version:
        template: python/generate_version
        requires: [
            validate_test, validate_lint, validate_codestyle, validate_dependencies, validate_security, 
            # validate_type
        ]

    publish_test_pypi:
        template: python/package_python
        environment:
            PUBLISH: True
            TWINE_REPOSITORY_URL: https://test.pypi.org/legacy/
        requires: [version]

    verify_test_package:
        template: python/validate_pypi_package
        environment:
            PYPI_INDEX_URL: https://test.pypi.org/simple
        requires: [publish_test_pypi]

    publish_pypi:
        template: python/package_python
        environment:
            PUBLISH: True
        requires: [verify_test_package]

    publish_documentation:
        template: python/documentation
        requires: [publish_pypi]
