# Copyright 2019, Oath Inc.
# Licensed under the terms of the Apache 2.0 license.  See the LICENSE file in the project root for terms

version: 4
shared:
    environment:
        CHANGELOG_FILENAME: docs/changelog.md
        DOCUMENTATION_DEBUG: True
        DOCUMENTATION_FORMATS: mkdocs
        # PACKAGE_DIR: src
        # PACKAGE_DIRECTORY: src
    steps:
        - tag_release: $BASE_PYTHON -m screwdrivercd.repo.release

jobs:
    validate_codestyle:
        template: python/validate_codestyle
        environment:
            CODESTYLE_ARGS: -v
        steps:
            - postinstall_dependencies: $BASE_PYTHON -m pip install -U .
        requires: [~commit, ~pr]

    validate_dependencies:
        template: python/validate_dependencies
        requires: [~commit, ~pr]

    validate_lint:
        template: python/validate_lint
        requires: [~commit, ~pr]

    validate_security:
        template: python/validate_security
        requires: [~commit, ~pr]

    validate_test:
        template: python/validate_unittest
        steps:
            - postupdate_version: |
                PACKAGE_VERSION="`meta get package.version`"
                echo $PACKAGE_VERSION
            - preend: meta set package.version "$PACKAGE_VERSION"
        requires: [~commit, ~pr]

    # The newest version of mypy appears to be broken in a manner that it always flags a specific valid type
    # annotation.
    # validate_type:
    #    template: python/validate_type
    #     requires: [~commit, ~pr]

    validate_documentation:
        template: python/documentation
        steps:
            - publish_documentation: |
                LOGDIR="$SD_ARTIFACTS_DIR/logs/$SD_TEMPLATE_NAME"
                if [ ! -e "$LOGDIR" ]; then
                    mkdir -p "$LOGDIR"
                fi
                echo "Installing screwdrivercd documentation extras"
                $BASE_PYTHON -m pip install screwdrivercd[documentation] 2>&1 | tee -a $LOGDIR/install_screwdrivercd_extra_documentation.log
                $BASE_PYTHON << EOF
                import json
                import os
                import sys
                from screwdrivercd.utility.package import PackageMetadata

                extras = []
                if os.path.exists('setup.py'):
                    package = PackageMetadata()
                    extras = list(package.metadata.get('provides_extras', set()))
                    if 'doc_build' in extras:
                        with open('/tmp/doc_build_has_extras', 'w') as fh:
                            json.dump(extras, fh)
                EOF
                if [ -e "/tmp/doc_build_has_extras" ]; then
                    $BASE_PYTHON -m pip install .[doc_build] 2>&1 | tee -a $LOGDIR/install_package_extra_doc_build.log
                fi
                $BASE_PYTHON -m screwdrivercd.documentation
        requires: [~pr]

    version:
        template: python/generate_version
        requires: [
            validate_test, validate_lint, validate_codestyle, validate_dependencies, validate_security, 
            # validate_type
        ]

    publish_test_pypi:
        template: python/package_python
        environment:
            PUBLISH: True
            TWINE_REPOSITORY_URL: https://test.pypi.org/legacy/
        requires: [version]

    verify_test_package:
        template: python/validate_pypi_package
        environment:
            PYPI_INDEX_URL: https://test.pypi.org/simple
        requires: [publish_test_pypi]

    publish_pypi:
        template: python/package_python
        environment:
            PUBLISH: True
        requires: [verify_test_package]

    publish_documentation:
        template: python/documentation
        requires: [publish_pypi]
