# Copyright 2019, Oath Inc.
# Licensed under the terms of the Apache 2.0 license.  See the LICENSE file in the project root for terms

version: 4
shared:
    environment:
        CHANGELOG_FILENAME: docs/changelog.md
        DOCUMENTATION_DEBUG: True
        DOCUMENTATION_FORMATS: mkdocs
    steps:
        - tag_release: $BASE_PYTHON -m screwdrivercd.repo.release

jobs:
    validate_codestyle:
        template: python/validate_codestyle
        environment:
            CODESTYLE_ARGS: -v
        steps:
            - postinstall_dependencies: $BASE_PYTHON -m pip install -U .
        requires: [~commit, ~pr]

    validate_lint:
        template: python/validate_lint
        requires: [~commit, ~pr]

    validate_test:
        template: python/validate_unittest
        steps:
            - postupdate_version: |
                PACKAGE_VERSION="`meta get package.version`"
                echo $PACKAGE_VERSION
            - preend: meta set package.version "$PACKAGE_VERSION"
        requires: [~commit, ~pr]
        
    version:
        template: python/generate_version
        requires: [
            validate_test, validate_lint, validate_codestyle
        ]

    publish_test_pypi:
        template: python/package_python
        environment:
            PUBLISH: True
            TWINE_REPOSITORY_URL: https://test.pypi.org/legacy/
        requires: [version]

    verify_test_package:
        template: python/validate_pypi_package
        environment:
            PYPI_INDEX_URL: https://test.pypi.org/simple
        requires: [publish_test_pypi]

    publish_pypi:
        template: python/package_python
        environment:
            PUBLISH: True
        requires: [verify_test_package]

    publish_documentation:
        template: python/documentation
        steps:
            - postinstall_dependencies: |
                $BASE_PYTHON -m pip install -U .
                printenv | grep SD | sort
        requires: [~pr, ~publish_pypi]
